#!/usr/bin/env python3
"""
Regenerate the "Directory Structure" tree in README.md from `git ls-files`, so the tree never drifts
from what the kit actually ships.

The tree lives between these two markers in README.md:
    <!-- tree:begin (generated by scripts/gen-readme-tree.py, do not edit by hand) -->
    <!-- tree:end -->

Run from the repo root after you add, remove or rename a tracked file:
    python3 scripts/gen-readme-tree.py            # rewrite README.md in place
    python3 scripts/gen-readme-tree.py --check    # exit 1 if README.md is out of date (no write)
    python3 scripts/gen-readme-tree.py --count    # print the tracked-file count (for the docs that quote it)

Only tracked files appear, so untracked scratch files never leak into the tree. Files without an entry
in COMMENTS are listed without a comment; add one here when you add a file worth explaining.
"""
import subprocess
import sys
from pathlib import Path

BEGIN = "<!-- tree:begin (generated by scripts/gen-readme-tree.py, do not edit by hand) -->"
END = "<!-- tree:end -->"

# One-line notes shown next to a path. Keys are repo-relative paths.
COMMENTS = {
    "rules/communication.md": "Voice standards, anti-slop, banned words",
    "rules/security.md": "Access control, secrets, input validation, agent pointer",
    "rules/architecture.md": "Decision framework, patterns",
    "rules/code-quality.md": "Code standards",
    "rules/testing-quality.md": "Tests that catch bugs; proof-artifact and persistence proof",
    "rules/proof-before-claim.md": "Proof family: done needs a signal from the running system",
    "rules/findings-are-perishable.md": "Proof family: re-check old findings",
    "rules/claims-faithful-to-source.md": "Proof family: claims match their source",
    "rules/refutation-needs-the-right-oracle.md": "Proof family: check the right source before saying it's false",
    "rules/structural-voice.md": "Structure-level anti-AI rules",
    "rules/agent-security-boundary.md": "Agents that read outside data and hold tools: data is not instructions, default-deny egress",
    "rules/tiered-orchestration.md": "Match model, effort and tool to the task; verify anything cheap",
    "rules/context-mode-policy.md": "When to use a context-compression plugin and when to read directly",
    "hooks/scripts/session-init.py": "SessionStart: context routing",
    "hooks/scripts/guardrail.py": "PreToolUse: block dangerous commands",
    "hooks/scripts/domain-verification.py": "PreToolUse: flag hallucinated terms from your field",
    "hooks/scripts/schema-check.py": "PreToolUse: check SQL columns against your schema",
    "hooks/scripts/output-quality-gate.py": "PostToolUse: scan for AI-slop in written files",
    "hooks/scripts/voice-tell-gate.py": "Pre+PostToolUse: voice engine on sends (blocks) and written files (nudges)",
    "hooks/scripts/voice-draft-gate.py": "Stop: checks a draft shown in chat (```draft fence) with the send hook's scorer",
    "hooks/scripts/graph-auto-index.py": "Knowledge-graph indexer; installed, not wired by default",
    "hooks/scripts/deploy-proof-gate.py": "PostToolUse: after a deploy, prove it on the running system",
    "hooks/scripts/claim-faithfulness-gate.py": "PostToolUse, opt-in: re-read claims against their sources",
    "hooks/scripts/refutation-oracle-gate.py": "PostToolUse, opt-in: check the right source before calling something fabricated",
    "crons/manage.sh": "Install / uninstall / status / test (launchd)",
    "crons/gather/web-scan.py": "Exa web scan (needs EXA_API_KEY)",
    "crons/gather/hn-scan.py": "Hacker News scan (no key)",
    "crons/gather/github-scan.py": "GitHub releases + trending (no key)",
    "crons/plists/com.context.gather.web.plist": "launchd schedule for the web scan (4:30 AM)",
    "crons/plists/com.context.gather.hn.plist": "launchd schedule for the Hacker News scan (4:45 AM)",
    "crons/plists/com.context.gather.github.plist": "launchd schedule for the GitHub scan (4:50 AM)",
    "crons/plists/com.context.synthesize.morning.plist": "launchd schedule for the morning digest (5:00 AM)",
    "crons/synthesize/morning-digest.sh": "Synthesizes gathered files into wiki/inbox.md",
    "crons/synthesize/memory-decay-check.sh": "Flags memory files unchanged for 45+ days (no plist)",
    "crons/curate-prep/curate-prep.py": "Read-only weekly prep for /curate (writes CURATE-PENDING.md)",
    "crons/backup/backup-sessions.sh": "Local mirror + dated snapshots of session transcripts (opt-in)",
    "crons/plists/com.context.curate-prep.plist": "launchd schedule for curate-prep (Sundays 11:00 PM)",
    "crons/plists/com.context.session-backup.plist": "launchd schedule for the backup; only with install --with-backup",
    "hooks/selftest.py": "Feeds synthetic payloads to every hook and checks the output contract",
    "hooks/tests/test_proof_gates.py": "Tests for the three proof-family hooks",
    "templates/wiki/log.md": "Append-only wiki change log",
    "templates/memory/README.md": "Memory folder conventions: frontmatter, tiered index, perishable fields",
    "wiki/README.md": "Wiki layout and the local-only page convention",
    "wiki/index.md": "Wiki index (setup --with-wiki copies it)",
    "templates/CLAUDE.md": "Identity template with routing table",
    "templates/apps-script/email-merge.gs": "Mail merge from a Sheet (dry run by default)",
    "templates/apps-script/sheet-data-puller.gs": "A Sheet as a JSON endpoint",
    "templates/apps-script/slides-from-sheet.gs": "One slide per Sheet row",
    "QUICKSTART-PROMPT.md": "Paste into Claude Code to write your CLAUDE.md",
    "VOICE-ONBOARDING.md": "Calibrate the voice guard to you (/voice-setup, short version)",
    "WHAT-YOU-GET.md": "Full inventory",
    "settings.json.example": "Reference only; setup wires hooks for you. Merge by hand, never copy over yours",
    "setup.sh": "Installer (safe to re-run: upgrades what you never edited)",
}

# Directory notes shown on the directory line itself.
DIR_COMMENTS = {
    "tools": "Voice engine (scorer, normalizer, gate, send hook and draft gate source, /voice-setup tools, calibration), RAG-quality and transcript-export tools",
    "harness-evolution": "Held-out eval harness + your voice corpus",
    "scripts": "llm-call.py + llm-review.py back /review and /validate (LLM_BASE_URL, LLM_API_KEY)",
    "scripts/": "Repo-only helpers: hook wiring, manifest and tree generators, install, cron and script tests",
    "rules-optional": "Opt-in design rules (Tailwind, Delta); setup never copies them",
    "tests": "Tests for the crons, transcript export and graph indexer",
    "examples": "Worked examples",
    "docs": "Inventory page, recommended plugins, Apps Script guide, voice system docs and site (docs/voice/)",
    "site": "The GitHub Pages site (the Part 6 article)",
    "guards": "Working controls for agents (egress, broker, reducer, path protection, leak scan) with tests",
    "wiki": "Starter wiki skeleton",
    "templates": "CLAUDE.md, memory, wiki log and report templates",
    "crons": "Optional overnight intelligence",
    ".github": "Pages deploy workflow, issue templates",
    "hooks": "Hook sources (setup installs hooks/scripts/)",
    "workflows": "Multi-agent audit workflows behind /claim-audit, /plan-audit, /execution-truth, /provenance-audit",
}

# (install destination under ~/.claude/, repo source dir, glob suffix)
INSTALLED = [
    ("rules", "rules", ".md"),
    ("hooks/scripts", "hooks/scripts", ".py"),
    ("commands", "skills", ".md"),
]
# Trees setup copies whole (see setup.sh step 5): shown as one line each.
INSTALLED_TREES = ["tools", "harness-evolution", "workflows"]
INSTALLED_SCRIPTS = ["scripts/llm-call.py", "scripts/llm-review.py", "scripts/review-prompts"]

# Repo dirs listed file by file in the "not installed" section; everything else shows as a directory line.
EXPAND = ["crons", "templates", "hooks", "wiki"]

# Install plumbing that doesn't belong in a reader-facing tree.
PLUMBING = {".gitignore", "hooks/prior-kit-hashes.txt", "install-prior-hashes.txt"}


def tracked():
    out = subprocess.run(["git", "ls-files"], capture_output=True, check=True).stdout.decode()
    return sorted(f for f in out.split("\n") if f)


def note(path, table=COMMENTS):
    c = table.get(path)
    return f"  # {c}" if c else ""


def nested(paths):
    root = {}
    for p in paths:
        node = root
        parts = p.split("/")
        for part in parts[:-1]:
            node = node.setdefault(part + "/", {})
        node[parts[-1]] = p
    return root


def render(node, prefix=""):
    lines = []
    items = sorted(node.items(), key=lambda kv: (not kv[0].endswith("/"), kv[0]))
    for i, (name, child) in enumerate(items):
        last = i == len(items) - 1
        branch = "+-- " if last else "|-- "
        cont = "    " if last else "|   "
        if isinstance(child, dict):
            lines.append(f"{prefix}{branch}{name}")
            lines.extend(render(child, prefix + cont))
        else:
            lines.append(f"{prefix}{branch}{name}{note(child)}")
    return lines


def build(files):
    fs = set(files)
    out = ["~/.claude/   (what ./setup.sh installs)"]
    entries = []  # (label, [lines])
    for dest, src, suffix in INSTALLED:
        names = sorted(f.split("/")[-1] for f in files if f.startswith(src + "/") and f.count("/") == src.count("/") + 1 and f.endswith(suffix))
        tree = {n: f"{src}/{n}" for n in names}
        entries.append((dest + "/", render(tree)))
    for t in INSTALLED_TREES:
        n = sum(1 for f in files if f.startswith(t + "/"))
        if n == 0:
            continue  # a tree this checkout doesn't have yet
        entries.append((f"{t}/  ({n} files){note(t, DIR_COMMENTS)}", []))
    sc = []
    for s in INSTALLED_SCRIPTS:
        if s in fs or any(f.startswith(s + "/") for f in files):
            sc.append(s.split("/", 1)[1] + ("/" if s not in fs else ""))
    entries.append((f"scripts/  ({', '.join(sc)}){note('scripts', DIR_COMMENTS)}", []))
    entries.append(("CLAUDE.md, settings.json  # yours: write CLAUDE.md with QUICKSTART-PROMPT.md, merge settings by hand", []))
    entries.append(("projects/<project>/memory/  # Claude Code creates this itself", []))
    for i, (label, lines) in enumerate(entries):
        last = i == len(entries) - 1
        out.append(("+-- " if last else "|-- ") + label)
        pad = "    " if last else "|   "
        out.extend(pad + ln for ln in lines)
    out.append("")
    out.append("In the repo, not installed by setup")
    installed_prefixes = (
        "rules/", "skills/", "tools/", "harness-evolution/", "workflows/", "hooks/scripts/",
    )
    tree = {}
    counts = {}
    for f in files:
        if f.startswith(installed_prefixes) or f in PLUMBING:
            continue
        if any(f == s or f.startswith(s + "/") for s in INSTALLED_SCRIPTS):
            continue  # shown in the installed section
        parts = f.split("/")
        if len(parts) == 1:
            tree[f] = f
        elif any(f.startswith(e + "/") for e in EXPAND):
            node = tree
            for part in parts[:-1]:
                node = node.setdefault(part + "/", {})
            if not parts[-1] == ".gitkeep":
                node[parts[-1]] = f
        else:
            counts[parts[0]] = counts.get(parts[0], 0) + 1
    for d, n in counts.items():
        tree[d + "/"] = f"__count__{n}"
    lines = []
    items = sorted(tree.items(), key=lambda kv: (not kv[0].endswith("/"), kv[0]))
    for i, (name, child) in enumerate(items):
        last = i == len(items) - 1
        branch = "+-- " if last else "|-- "
        cont = "    " if last else "|   "
        if isinstance(child, dict):
            lines.append(f"{branch}{name}{note(name.rstrip('/'), DIR_COMMENTS)}")
            lines.extend(render(child, cont))
        elif child.startswith("__count__"):
            dnote = DIR_COMMENTS.get(name) or DIR_COMMENTS.get(name.rstrip('/'))
            lines.append(f"{branch}{name}" + (f"  # {dnote}" if dnote else "") + f"  ({child[9:]} file{'' if child[9:] == '1' else 's'})")
        else:
            lines.append(f"{branch}{name}{note(child)}")
    out.extend(lines)
    return align(out)


def align(lines, col=52):
    """Pad trailing '  # note' comments to one column (lines already past it keep two spaces)."""
    out = []
    for ln in lines:
        if "  # " in ln:
            left, right = ln.split("  # ", 1)
            out.append(left.ljust(col) + "  # " + right if len(left) < col else left + "  # " + right)
        else:
            out.append(ln)
    return out


def main():
    files = tracked()
    if "--count" in sys.argv:
        print(len(files))
        return 0
    block = BEGIN + "\n```\n" + "\n".join(build(files)) + "\n```\n" + END
    readme = Path("README.md")
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        sys.exit("README.md is missing the tree:begin / tree:end markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + block + tail
    if "--check" in sys.argv:
        if new != text:
            print("README.md tree is out of date: run python3 scripts/gen-readme-tree.py")
            return 1
        print("README.md tree is current")
        return 0
    readme.write_text(new)
    print(f"README.md tree rewritten from {len(files)} tracked files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
